Traceback (most recent call last):
  File "/home/codespace/.local/lib/python3.12/site-packages/jupyter_core/utils/__init__.py", line 154, in wrapped
    asyncio.get_running_loop()
RuntimeError: no running event loop

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/python/3.12.1/lib/python3.12/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/home/codespace/.local/lib/python3.12/site-packages/nbclient/client.py", line 1319, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/codespace/.local/lib/python3.12/site-packages/jupyter_core/utils/__init__.py", line 158, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/python/3.12.1/lib/python3.12/asyncio/base_events.py", line 684, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/codespace/.local/lib/python3.12/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/home/codespace/.local/lib/python3.12/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/codespace/.local/lib/python3.12/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
if not os.path.exists(CSV_PATH):
    raise FileNotFoundError(f"File tidak ditemukan: {CSV_PATH}")

df = pd.read_csv(CSV_PATH)

if MERGE_TITLE and "judul"  in df.columns and "berita" in df.columns:
    df['text'] = df['judul'].fillna('') + ". " + df['berita'].fillna('')
elif "berita" in df.columns:
    df['text'] = df['berita'].fillna('')
else:
    raise ValueError("Kolom 'berita' tidak ditemukan.")

if "kategori" not in df.columns:
    raise ValueError("Kolom 'kategori' (label) tidak ditemukan.")
------------------


[31m---------------------------------------------------------------------------[39m
[31mFileNotFoundError[39m                         Traceback (most recent call last)
[36mCell[39m[36m [39m[32mIn[6][39m[32m, line 2[39m
[32m      1[39m [38;5;28;01mif[39;00m [38;5;129;01mnot[39;00m os.path.exists(CSV_PATH):
[32m----> [39m[32m2[39m     [38;5;28;01mraise[39;00m [38;5;167;01mFileNotFoundError[39;00m([33mf[39m[33m"[39m[33mFile tidak ditemukan: [39m[38;5;132;01m{[39;00mCSV_PATH[38;5;132;01m}[39;00m[33m"[39m)
[32m      4[39m df = pd.read_csv(CSV_PATH)
[32m      6[39m [38;5;28;01mif[39;00m MERGE_TITLE [38;5;129;01mand[39;00m [33m"[39m[33mjudul[39m[33m"[39m  [38;5;129;01min[39;00m df.columns [38;5;129;01mand[39;00m [33m"[39m[33mberita[39m[33m"[39m [38;5;129;01min[39;00m df.columns:

[31mFileNotFoundError[39m: File tidak ditemukan: Berita.csv

